# This file was generated by GoReleaser. DO NOT EDIT.
cask "tea-dash" do
  version "0.2.12"

  on_macos do
    on_intel do
      sha256 "6f62700d10f11b5775f4c258927eef755a4fd9c70630d435c053f5d487dfa5af"
      url "https://github.com/gbarany/tea-dash/releases/download/v#{version}/tea-dash_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f2365a11ddb246a2891d4163815abe9d95410c1944e2b987ae575837a5473436"
      url "https://github.com/gbarany/tea-dash/releases/download/v#{version}/tea-dash_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "32106341de0bf3180bb587786f7c7b0de3abc266e382fcaa0a4fc700c25ca4f5"
      url "https://github.com/gbarany/tea-dash/releases/download/v#{version}/tea-dash_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "265a99e783b83644a5225af96e23ade7f8b5bf84e78ded84824796d04626b37c"
      url "https://github.com/gbarany/tea-dash/releases/download/v#{version}/tea-dash_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tea-dash"
  desc "Terminal dashboard for Gitea/Forgejo, in the spirit of gh-dash"
  homepage "https://github.com/gbarany/tea-dash"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tea-dash"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tea-dash"]
    end
  end

  # No zap stanza required

end
