# This file was generated by GoReleaser. DO NOT EDIT.
cask "tea-dash" do
  version "0.3.3"

  on_macos do
    on_intel do
      sha256 "699011298f2881026d7590c9462d5d8b6d39e0762f2585b7f5fb06463e4c058b"
      url "https://github.com/gbarany/tea-dash/releases/download/v#{version}/tea-dash_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ff4d6853029b1d71c051f367f37f6375dad4698d2d11bfe80e700db60c3ef3b3"
      url "https://github.com/gbarany/tea-dash/releases/download/v#{version}/tea-dash_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "78bfe2ce1914254c82723d6cb3da7266379efea9837fb60eb7fefc45be582522"
      url "https://github.com/gbarany/tea-dash/releases/download/v#{version}/tea-dash_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "871abe77b65b0870c142ceb721d232f2fa84f16710a2bb4f1e494144cc8c965d"
      url "https://github.com/gbarany/tea-dash/releases/download/v#{version}/tea-dash_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tea-dash"
  desc "Terminal dashboard for Gitea/Forgejo, in the spirit of gh-dash"
  homepage "https://github.com/gbarany/tea-dash"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tea-dash"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tea-dash"]
    end
  end

  # No zap stanza required

end
