# This file was generated by GoReleaser. DO NOT EDIT.
cask "tea-dash" do
  version "0.3.9"

  on_macos do
    on_arm do
      sha256 "22276b93d88deb6b6753772629b34dcc4f01da0b82c33d19f6bde83d094045b1"
      url "https://github.com/gbarany/tea-dash/releases/download/v#{version}/tea-dash_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6ce41c36ed068411c94dc5671d67e0fc7f38e1383c1c15e103b2475cd08af826"
      url "https://github.com/gbarany/tea-dash/releases/download/v#{version}/tea-dash_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0bfe1fcfe228e81fc15f346161dc49bb907b046690e989aed7d313b65d48e69d"
      url "https://github.com/gbarany/tea-dash/releases/download/v#{version}/tea-dash_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1daebb421f0ba5fc95af5e1363d9d78b1fc22250d253ec9b539fb00f73596941"
      url "https://github.com/gbarany/tea-dash/releases/download/v#{version}/tea-dash_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tea-dash"
  desc "Terminal dashboard for Gitea/Forgejo, in the spirit of gh-dash"
  homepage "https://github.com/gbarany/tea-dash"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tea-dash"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tea-dash"]
    end
  end

  # No zap stanza required
end
